In [44]:
# Starting with fake stock prices

import numpy as np
import pandas as pd

prices = np.array([100, 102, 101, 105, 103])

print(prices)

[100 102 101 105 103]


In [45]:
# Calculating the simple returns

simple_returns = prices[1:] / prices[:-1] - 1

print(simple_returns)

[ 0.02       -0.00980392  0.03960396 -0.01904762]


In [46]:
# Calculating log returns

log_returns = np.log(prices[1:] / prices[:-1])

print(log_returns)

[ 0.01980263 -0.0098523   0.03883983 -0.01923136]


In [47]:
# Putting results in a table

df = pd.DataFrame({
    "Price": prices
})

df["Simple Return"] = df["Price"].pct_change()

df["Log Return"] = np.log(df["Price"] / df["Price"].shift(1))

print(df)

   Price  Simple Return  Log Return
0    100            NaN         NaN
1    102       0.020000    0.019803
2    101      -0.009804   -0.009852
3    105       0.039604    0.038840
4    103      -0.019048   -0.019231


In [48]:
# Adding mean and volatility

mean_return = df["Log Return"].mean()
volatility = df["Log Return"].std()

print("Mean daily log return", mean_return)
print("Daily volatility:", volatility)

Mean daily log return 0.0073897005603861116
Daily volatility: 0.02676539450596779


In [49]:
# Annualise the volatility

annual_volatility = volatility * np.sqrt(252)

print("Annualised volatility", annual_volatility)

Annualised volatility 0.4248874656319516
