In [35]:
# Starting with fake stock prices

import numpy as np
import pandas as pd

prices = np.array([100, 102, 101, 105, 103])

print(prices)

[100 102 101 105 103]


In [36]:
# Calculating the simple returns

simple_returns = prices[1:] / prices[:-1] - 1

print(simple_returns)

[ 0.02       -0.00980392  0.03960396 -0.01904762]


In [37]:
# Calculating log returns

log_returns = np.log(prices[1:] / prices[:-1])

print(log_returns)

[ 0.01980263 -0.0098523   0.03883983 -0.01923136]


In [38]:
# Putting results in a table

df = pd.DataFrame({
    "Price": prices
})

df["Simple Return"] = df["Price"].pct_change()

df["Log Return"] = np.log(df["Price"] / df["Price"].shift(1))

print(df)

   Price  Simple Return  Log Return
0    100            NaN         NaN
1    102       0.020000    0.019803
2    101      -0.009804   -0.009852
3    105       0.039604    0.038840
4    103      -0.019048   -0.019231
